---
title: "Retention Index Additional Analyses"
author: "Degnan, David J. & Bramer, Lisa M. & Flores, Javier E."
date: "Last updated: 03/16/2023"
output:
  BiocStyle::html_document:
    toc_float: true
    code_folding: hide
    lib_dir: trelli
---

```{r Setup, include=FALSE}
path <- "~/Git_Repos/metabolomics_retention_index_score/Markdowns/6-Retention-Index-Additional-Analyses/"
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(rootdir = path)
library(dplyr)
library(data.table)
library(ggplot2)
library(patchwork)
library(e1071)
```

```{r Load Data}
# Anno30 
Annotations <- fread("~/Downloads/AnnoTP.txt")

# Count the metabolite data 
MetaboliteCount <- table(Annotations$`Compound Name`, dnn = c("Compound.Name")) %>%
  data.frame() %>%
  mutate("Label" = ifelse(Freq >= 30, ">=30", "<30"))

# Number of metabolites greater than or equal to 30 samples
MetaboNum <- nrow(MetaboliteCount[MetaboliteCount$Freq >= 30,])

# Subset annotation data to only the top 30 metabolites
Anno30 <- Annotations[Annotations$`Compound Name` %in% 
                      MetaboliteCount[MetaboliteCount$Freq >= 30, "Compound.Name"],]
# List FAMES files 
FAMES_files <- list.files("../../RI_Specific_Data/TP_RI_with_FAMES", full.names = T)

# Pull data from files 
FAMES_TP <- do.call(rbind, lapply(FAMES_files, function(x) {
  
  # Read data, add column indicating FAMEs or not, and add dataset name
  Sub <- fread(x) %>%
    mutate(
      FAMES = grepl("FAME", `Sample Name`),
      Dataset = strsplit(x, "/", fixed = T) %>% unlist() %>% tail(1)
    )
  
  # Split out fames 
  FAME_Sub <- Sub %>% filter(FAMES)
  Sub <- Sub %>% filter(!FAMES)
  
  # Add left and right difference
  Res <- Sub %>%
    mutate(
      `Left FAMEs RT` = lapply(`Retention Time`, function(RT) {
        ifelse(RT < min(FAME_Sub$`Retention Time`), NA, 
               FAME_Sub$`Retention Time`[which(RT - FAME_Sub$`Retention Time` > 0) %>% max()])
      }) %>% unlist(),
      `Left FAMEs RI` = lapply(`Retention Index`, function(RI) {
        ifelse(RI < min(FAME_Sub$`Retention Index`), NA, 
               paste0("FAMES RI: ", FAME_Sub$`Retention Index`[which(RI - FAME_Sub$`Retention Index` > 0) %>% max()]))
      }) %>% unlist(),
      `Left Difference` = `Retention Time` - `Left FAMEs RT`,
      `Right FAMEs RT` = lapply(`Retention Time`, function(RT) {
        ifelse(RT > max(FAME_Sub$`Retention Time`), NA, 
               FAME_Sub$`Retention Time`[which(FAME_Sub$`Retention Time` - RT > 0) %>% min()])
      }) %>% unlist(),
      `Right FAMEs RI` = lapply(`Retention Index`, function(RI) {
        ifelse(RI > max(FAME_Sub$`Retention Index`), NA, 
               paste0("FAMES RI: ", FAME_Sub$`Retention Index`[which(FAME_Sub$`Retention Index` - RI > 0) %>% min()]))
      }) %>% unlist(),
      `Right Difference` = `Right FAMEs RT` - `Retention Time`
    )
  
  return(Res)

}))

# Pull Skews
Skew <- FAMES_TP %>%
  dplyr::select(`Compound Name`, `Retention Index`) %>%
  group_by(`Compound Name`) %>%
  summarise(`Absolute Skew` = abs(skewness(`Retention Index`)))

# Merge skew
FAMES_TP <- merge(FAMES_TP, Skew, by = "Compound Name")

FAMES_TP <- FAMES_TP %>% mutate(`Max Difference` = lapply(1:nrow(FAMES_TP), function(el) {
  max(c(FAMES_TP$`Left Difference`[el], FAMES_TP$`Right Difference`[el]), na.rm = T)
}) %>% unlist())
```

## Are non-normal distributions far from FAMES?

In short, there does not appear to be a relationship between distance from FAMEs
and normality. 

```{r}
# Clean up FAMES TP 
Left_FAMES <- FAMES_TP %>% 
  filter(!is.na(`Left FAMEs RI`)) %>%
  rename(`Retention Time Difference` = `Left Difference`) %>%
  mutate(
    `Left FAMEs RI` = factor(`Left FAMEs RI`, 
                             levels = paste0("FAMES RI: ", c("800", "900", "1000", "1200", 
                                                             "1400", "1600", "1800", "2000", 
                                                             "2200", "2400")))
  )

Left_Plot <- ggplot(Left_FAMES, aes(x = `Retention Time Difference`, y = `Absolute Skew`)) + geom_point() + theme_bw() +
  facet_wrap(.~`Left FAMEs RI`) + ggtitle("Left Distance from FAMEs") + 
  theme(plot.title = element_text(hjust = 0.5))

Left_Plot
```

```{r}
Right_FAMES <- FAMES_TP %>% 
  filter(!is.na(`Right FAMEs RI`)) %>%
  rename(`Retention Time Difference` = `Right Difference`) %>%
  mutate(
    `Right FAMEs RI` = factor(`Right FAMEs RI`, 
                             levels = paste0("FAMES RI: ", c("800", "900", "1000", "1200", 
                                                             "1400", "1600", "1800", "2000", 
                                                             "2200", "2400", "2600")))
  )

Right_Plot <- ggplot(Right_FAMES, aes(x = `Retention Time Difference`, y = `Absolute Skew`)) + geom_point() + theme_bw() +
  facet_wrap(.~`Right FAMEs RI`) + ggtitle("Right Distance from FAMEs") + 
  theme(plot.title = element_text(hjust = 0.5))

Right_Plot
```

## Do we see retention time drift since FAMEs injection time? 

```{r}
FAMES_files <- list.files("../../RI_Specific_Data/TP_RI_with_FAMES", full.names = T)
Metadata <- fread("../../Metadata/Sample_Metadata.csv")
Metadata$Time <- as.Date(Metadata$Time, "%m/%d/%y")

FAMES_Drift <- do.call(rbind, lapply(FAMES_files, function(x) {
  
  # Read data, add column indicating FAMEs or not, and add dataset name
  Sub <- fread(x) %>%
    mutate(
      FAMES = grepl("FAME", `Sample Name`),
      Dataset = strsplit(x, "/", fixed = T) %>% unlist() %>% tail(1)
    ) %>%
    merge(Metadata, by = "Sample Name")
  
  # Split out fames 
  FAME_Sub <- Sub %>% filter(FAMES)
  Sub <- Sub %>% filter(!FAMES)
  
  # Get time elapsed
  Sub$`Time Elapsed` <- abs(Sub$Time - FAME_Sub$Time[1])
  
  return(Sub)
  
}))
  
Metabolite_Drift_Plot <- ggplot(FAMES_Drift, aes(x = `Time Elapsed`, y = `Retention Time`, group = `Compound Name`)) + geom_line() +
  geom_point() + theme_bw() + theme(legend.position = "none") + xlab("Days since FAMEs injection") 

Metabolite_Drift_Plot
```

We do not. 

```{r}
# Load FAMES data 
FAMES <- fread("../../RI_Specific_Data/FAMES.csv")

# Extract times 
FAMES$Date <- FAMES$`Sample name` %>%
  strsplit("_") %>%
  lapply(function(x) tail(x, 1)) %>%
  unlist() %>%
  as.Date("%Y%m%d")

# Simplify name
FAMES$FAME <- FAMES$`Compound Name` %>%
  strsplit("]", fixed = T) %>%
  lapply(function(x) {x <- head(x, 1)
                      gsub("[", "", x, fixed = T)}) %>%
  unlist()
FAMES$FAME <- factor(FAMES$FAME, levels = c("C28", "C26", "C24", "C22", "C20", "C18",
                                            "C16", "C14", "C12", "C10", "C9", "C8"))

FAMES_Drift_Plot <- FAMES %>%
  ggplot(aes(x = Date, y = `Retention Time`, color = FAME)) + 
  geom_point() + theme_bw()


FAMES_Drift_Plot 
```

# Supplemental Figures 

## FAMES Standards Supplemental Figure

```{r}
Left_Plot + Right_Plot + plot_annotation(tag_levels = 'A')
```

## Identifying Any Drift

```{r}
Metabolite_Drift_Plot + FAMES_Drift_Plot + plot_annotation(tag_levels = 'A')
```

## Example Workflow

```{r}
Annotations <- fread("~/Downloads/AnnoTP.txt")

# Experimental Plot 
SampleCounts <- table(Annotations$`Sample Name`, dnn = "Sample") %>% data.frame()

Spectra_Exp <- Annotations %>%
  filter(`Sample Name` == "A_nidulans_glucuronicAcid_PO_03_M") %>%
  dplyr::select(`Retention Time`, `Peak Area`)

Spectra_Exp <- pspecterlib::make_peak_data(
  MZ = c(Spectra_Exp$`Retention Time`, 29),
  Intensity = c(Spectra_Exp$`Peak Area`, 1e6)
) 

Spectra_Exp_Plot <- (Spectra_Exp %>%
  pspecterlib::annotated_spectrum_plot()) + xlab("Retention Time") + 
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank()) + 
  ggtitle("Sample Chromatogram") + theme(plot.title = element_text(hjust = 0.5)) + xlim(c(5, 30))

Scale <- max(Spectra_Exp$Intensity)

# FAMES Plot 
FAMES_Exp <- pspecterlib::make_peak_data(
  MZ = c(7.88220, 9.255235, 10.62827, 13.22422, 15.58247, 17.72805, 19.67970, 21.48123,
         23.42395, 25.36667, 27.30939, 29.25211, rnorm(25, 18, 5)),
  Intensity = c(Scale * 0.2, Scale * 0.4, Scale * 0.6, Scale * 0.75, Scale, Scale * 0.77, 
                Scale * 0.8, Scale * 0.6, Scale * 0.77, Scale * 0.85, Scale * 0.98, Scale * 0.99,
                abs(rnorm(25, Scale * 0.1, 1e7)))
) 

class(FAMES_Exp) <- c("data.table", "data.frame")
FAMES_Exp$Group <- "Noise"
FAMES_Exp[FAMES_Exp$`M/Z` %in% c(7.88220, 9.255235, 10.62827, 13.22422, 15.58247, 17.72805, 19.67970, 21.48123,
         23.42395, 25.36667, 27.30939, 29.25211), "Group"] <- "FAMES"
Peaks <- FAMES_Exp
Peaks0 <- data.table::data.table(`M/Z` = c(Peaks$`M/Z` - 
    1e-12, Peaks$`M/Z` + 1e-12), Intensity = 0, Abundance = 0, Group = rep(FAMES_Exp$Group, 3))
Peaks <- rbind(Peaks0, Peaks)
Peaks <- Peaks[order(Peaks$`M/Z`), ]

FAMES_Exp_Plot <- ggplot(Peaks, aes(x = `M/Z`, y = Intensity, color = Group)) + geom_line(size = 1) +
  theme_bw() + scale_color_manual(values = c("red", "black")) +   
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank()) + 
  ggtitle("FAMEs Chromatogram") + theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
  xlab("Retention Time") + xlim(c(5, 30))

Spectra_Exp_Plot + FAMES_Exp_Plot
```

```{r}
Combined <- pspecterlib::make_peak_data(
  MZ = c(7.88220, 9.255235, 10.62827, 13.22422, 15.58247, 17.72805, 19.67970, 21.48123,
         23.42395, 25.36667, 27.30939, 29.25211, Spectra_Exp$`M/Z`, 29),
  Intensity = c(rep(3e8, 12),
                Spectra_Exp$Intensity, 1e6)
) 
class(Combined) <- c("data.table", "data.frame")
Combined$Group <- "Noise"
Combined[Combined$`M/Z` %in% c(7.88220, 9.255235, 10.62827, 13.22422, 15.58247, 17.72805, 19.67970, 21.48123,
         23.42395, 25.36667, 27.30939, 29.25211), "Group"] <- "FAMES"
Peaks <- Combined
Peaks0 <- data.table::data.table(`M/Z` = c(Peaks$`M/Z` - 
    1e-12, Peaks$`M/Z` + 1e-12), Intensity = 0, Abundance = 0, Group = rep(Combined$Group, 3))
Peaks <- rbind(Peaks0, Peaks)
Peaks <- Peaks[order(Peaks$`M/Z`), ]

Combined_Plot <- ggplot(Peaks, aes(x = `M/Z`, y = Intensity, color = Group)) + geom_line(size = 1) +
  theme_bw() + scale_color_manual(values = c("red", "black")) +   
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
  xlab("Retention Time") + xlim(c(5, 30))

Combined_Plot

```

```{r}
Anno30 %>%
  group_by(`Compound Name`) %>%
  summarise(
    SD = sd(`Retention Index`),
    Ref = `Retention Index Ref` %>% unique()
  ) %>%
  ggplot(aes(x = Ref, y = SD)) + geom_point() + theme_bw() + xlab("Reference Retention Index") +
  ylab("Query Retention Index Standard Deviation")


```



